version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-list
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meudb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: